# Site configuration
title: Cooking
description: Recipe Designer & Log
baseurl: ""
url: "https://bubbamurphy.com"

# Build settings
markdown: kramdown
theme: null

# --- NEW SECTION FOR RECIPES ---
collections:
  recipes:
    output: true
    permalink: /recipes/:path/
# -------------------------------

exclude:
 - Gemfile
 - Gemfile.lock
